SELECT AUTHOR_ID, 
(
    SELECT AUTHOR_NAME FROM AUTHOR A
    WHERE B.AUTHOR_ID = A.AUTHOR_ID
) AS AUTHOR_NAME,
CATEGORY, 
SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK B INNER JOIN BOOK_SALES S
WHERE 
    B.BOOK_ID = S.BOOK_ID
    AND
    SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;