SELECT A.CAR_ID, A.CAR_TYPE, 
    ROUND(A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
        AND B.START_DATE <= '2022-11-30'
        AND B.END_DATE >= '2022-11-01'
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = '30일 이상'
WHERE B.CAR_ID IS NULL
AND A.CAR_TYPE IN ('SUV', '세단')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;

