SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NOT NULL
AND LEFT(I.SEX_UPON_INTAKE, 6) LIKE 'Intact'
AND LEFT(O.SEX_UPON_OUTCOME, 6) NOT LIKE 'Intact'
ORDER BY I.ANIMAL_ID;