WITH HISTORY AS 
(SELECT H.HISTORY_ID, H.CAR_ID, C.DAILY_FEE,
 (CASE
  WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 AND DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
  WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 AND DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
  WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
  ELSE '할인 없음'
 END) AS DURATION_TYPE,
 DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭'),
DISCOUNT AS 
(SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭')

SELECT H.HISTORY_ID,
(CASE
WHEN H.DURATION_TYPE = '할인 없음' THEN H.DAILY_FEE * H.DIFF
 ELSE FLOOR(H.DAILY_FEE * (1 - 0.01 * D.DISCOUNT_RATE) * H.DIFF)
 END) AS FEE FROM HISTORY H
LEFT JOIN DISCOUNT D
ON H.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC, H.HISTORY_ID DESC;