WITH RECURSIVE TIME AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1
FROM TIME
WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME T
LEFT JOIN
(SELECT *, HOUR(DATETIME) AS HOUR FROM ANIMAL_OUTS) A
ON T.HOUR = A.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR;