SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN 
            (SELECT MEMBER_ID 
             FROM (SELECT *, DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS REVIEW_RANK
                FROM REST_REVIEW
                GROUP BY MEMBER_ID) INLINE
            WHERE REVIEW_RANK = 1
            ) 
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;


