# WITH MAX_LENGTH_TABLE AS (
#     SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEGNTH 
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# );

SELECT A.ID, N.FISH_NAME, A.LENGTH FROM FISH_INFO A
JOIN FISH_NAME_INFO N
ON A.FISH_TYPE = N.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) B
ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH;